for k,v in pairs(player.GetAll()) do 
    local a = v:LookupBone(&quot;ValveBiped.Bip01_Head1&quot;)
    local b = v:LookupBone(&quot;ValveBiped.Bip01_R_Thigh&quot;)
    local c = v:LookupBone(&quot;ValveBiped.Bip01_L_Thigh&quot;)
    local d = v:LookupBone(&quot;ValveBiped.Bip01_R_Calf&quot;)
    local e = v:LookupBone(&quot;ValveBiped.Bip01_L_Calf&quot;)
    local f = v:LookupBone(&quot;ValveBiped.Bip01_R_UpperArm&quot;)
    local g = v:LookupBone(&quot;ValveBiped.Bip01_L_UpperArm&quot;)
    local h = v:LookupBone(&quot;ValveBiped.Bip01_R_Forearm&quot;)
    local i = v:LookupBone(&quot;ValveBiped.Bip01_L_Forearm&quot;)
    local j = v:LookupBone(&quot;ValveBiped.Bip01_R_Clavicle&quot;)
    local k = v:LookupBone(&quot;ValveBiped.Bip01_L_Clavicle&quot;)

        v:ManipulateBoneScale( a, Vector(100,100,100)) 
        v:ManipulateBoneScale( b, Vector(100,100,100))
        v:ManipulateBoneScale( c, Vector(100,100,100))
        v:ManipulateBoneScale( d, Vector(100,100,100))
        v:ManipulateBoneScale( e, Vector(100,100,100))
        v:ManipulateBoneScale( f, Vector(100,100,100))
        v:ManipulateBoneScale( g, Vector(100,100,100))
        v:ManipulateBoneScale( h, Vector(100,100,100))
        v:ManipulateBoneScale( i, Vector(100,100,100))
        v:ManipulateBoneScale( j, Vector(100,100,100))
        v:ManipulateBoneScale( k, Vector(100,100,100))
        end